environment:
    install_berry_perl: "cmd /C git clone https://github.com/stevieb9/berrybrew && cd berrybrew/bin && berrybrew.exe install %version% && berrybrew.exe switch %version%"
    install_active_perl: "cmd /C choco install activeperl -version %version%"

    matrix:
      # 5.26: The first strawberry to use gmake instead of dmake by default.
      # test both 32/64 bit versions
      - install_perl: "%install_berry_perl%"
        version: "5.26.2_64"
      - install_perl: "%install_berry_perl%"
        version: "5.26.2_32"

      # 5.20: The first strawberry to come with PkgConfig.pm (installed as pkg-config)
      - install_perl: "%install_berry_perl%"
        version: "5.20.3_64"

      # 5.18: The last strawberry to not come with a pkg-config
      - install_perl: "%install_berry_perl%"
        version: "5.18.4_64"


install:
  # Install perl
  - cmd: "%install_perl%"
  # Make sure we are in project root
  - cmd: "cd %APPVEYOR_BUILD_FOLDER%"
  # Set path for berrybrew
  - SET PATH=C:\Perl5\bin;C:\berrybrew\%version%\c\bin;C:\berrybrew\%version%\perl\site\bin;C:\berrybrew\%version%\perl\bin;%PATH%
  - SET PERL5LIB=C:/Perl5/lib/perl5
  - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
  - SET PERL_MB_OPT=--install_base C:/Perl5
  - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
  - cpanm -n PerlIO::utf8_strict
  - cpanm -n Mixin::Linewise::Readers
  - cpanm -n Params::Validate
  - cpanm -n Getopt::Long::Descriptive
  - cpanm -n Log::Dispatch::Output Software::LicenseUtils Config::MVP::Reader::INI Config::MVP::Assembler Text::Template Data::Section App::Cmd::Tester Log::Dispatchouli MooseX::Types::Perl String::Formatter MooseX::SetOnce CPAN::Uploader Config::MVP::Section Perl::PrereqScanner App::Cmd::Setup Config::MVP::Reader Software::License Config::MVP::Reader::Findable::ByExtension Config::MVP::Reader::Finder Pod::Eventual Mixin::Linewise::Readers Config::MVP::Assembler::WithBundles App::Cmd::Command::version Config::INI::Reader App::Cmd::Tester::CaptureExternal Term::Encoding
  - cpanm -n Dist::Zilla
  - cpanm -n PkgConfig
  - cpanm Dist::Zilla::Plugin::Git::Check
  - dzil authordeps | cpanm -n
  - dzil listdeps | cpanm -n


build: off

test_script:
  - dzil test -v

shallow_clone: true

#matrix:
#  allow_failures:
#    - install_perl: "%install_active_perl%"
#      version: "5.24.1.2402"

cache:
  - C:\Perl5
