freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script:
    - sudo tzsetup America/New_York
    - sudo pkg install -y p5-Dist-Zilla p5-App-cpanminus git
    - sudo dzil authordeps --missing | cpanm -n
    - sudo dzil listdeps --missing | cpanm -n
    - sudo dzil run --no-build 'cpanm --installdeps .'
  script:
    - dzil test -v
  
