language: minimal
dist: xenial
services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/plicease/cip/main/bin/travis-bootstrap | bash
  - cip before-install

install:
  - cip diag
  - cip install
  - cip scn build

script:
  - cip script
  - ./maint/cip-test-plugins
  - cip scn run

jobs:
  include:
    - arch: arm64
      env: CIP_TAG=5.32-buster-arm64v8 ALIEN_BUILD_INSTALL_EXTRA=1 CIP_ENV=ALIEN_BUILD_LIVE_TEST=1

branches:
  only:
    - main

cache:
  directories:
    - "$HOME/.cip"
